export const productos = [
  {
    name: "Cepillo de diente",
    quantity: 10,
    batch: "Lote A",
    minStock: 10,
    dueDate: new Date("2023-5-30"),
  },
  {
    name: "Pasta dental",
    quantity: 5,
    batch: "Lote B",
    dueDate: new Date("2023-07-15"),
    minStock: 10,
  },
  {
    name: "Enjuage bucal",
    quantity: 8,
    batch: "Lote C",
    dueDate: new Date("2023-08-10"),
    minStock: 10,
  },
  {
    name: "Sonda exploradora",
    quantity: 15,
    minStock: 10,
    batch: "Lote D",
    dueDate: new Date("2023-09-20"),
  },
  {
    name: "Espejo dental",
    quantity: 12,
    batch: "Lote E",
    minStock: 10,
    dueDate: new Date("2023-10-05"),
  },
  {
    name: "Anestesia local",
    quantity: 20,
    minStock: 10,
    batch: "Lote F",
    dueDate: new Date("2023-10-15"),
  },
  {
    name: "Fórceps dental",
    quantity: 7,
    minStock: 10,
    batch: "Lote G",
    dueDate: new Date("2023-11-02"),
  },
  {
    name: "Composite dental",
    quantity: 25,
    minStock: 10,
    batch: "Lote H",
    dueDate: new Date("2023-11-20"),
  },
  {
    name: "Fresas dentales",
    quantity: 30,
    minStock: 10,
    batch: "Lote I",
    dueDate: new Date("2023-12-10"),
  },
  {
    name: "Placa de mordida",
    quantity: 10,
    minStock: 10,
    batch: "Lote J",
    dueDate: new Date("2024-01-05"),
  },
  {
    name: "Hilo dental",
    quantity: 50,
    minStock: 10,
    batch: "Lote K",
    dueDate: new Date("2024-01-15"),
  },
  {
    name: "Resina dental",
    quantity: 15,
    minStock: 10,
    batch: "Lote L",
    dueDate: new Date("2024-02-01"),
  },
];
